name: braacket-scraper
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - jupyter
  - ipywidgets
  - python-dotenv
  - polars
  - pyarrow
  - pandas
  - gql
  - requests-toolbelt
  - pip
  - pip:
    - trueskill
    - polars_ds
